# Generated by Django 5.2.17 on 2026-09-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.IntegerField(unique=True)),
                ('scheme_desc', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=100, unique=True)),
                ('reg_year', models.IntegerField()),
                ('reg_date', models.DateField()),
                ('worker_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('gender', models.IntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('caste', models.IntegerField()),
                ('nature_emp', models.IntegerField()),
                ('member_tradeunion', models.BooleanField(default=False)),
                ('migrantworker', models.IntegerField(blank=True, null=True)),
                ('migrant_state', models.IntegerField()),
                ('migrantdistrict', models.IntegerField()),
                ('migrantmandal', models.IntegerField()),
                ('reg_status', models.IntegerField()),
                ('valid_date', models.DateField()),
                ('marital_status', models.IntegerField()),
                ('distcode', models.IntegerField()),
                ('trno', models.BigIntegerField()),
                ('present_addr_district', models.IntegerField()),
                ('present_addr_mandal', models.IntegerField()),
                ('permenant_addr_district', models.IntegerField()),
                ('permenant_addr_mandal', models.IntegerField()),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscheme_code', models.IntegerField()),
                ('subscheme_desc', models.CharField(max_length=500)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subschemes', to='welfare.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=100)),
                ('trno', models.BigIntegerField()),
                ('claim_data_details', models.TextField(blank=True, default='')),
                ('remark', models.TextField(blank=True, default='')),
                ('dcl_remark', models.TextField(blank=True, default='')),
                ('created_dt', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=100)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='welfare.scheme')),
                ('subscheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='welfare.subscheme')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_applications', to='welfare.worker')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscheme',
            constraint=models.UniqueConstraint(fields=('scheme', 'subscheme_code'), name='unique_scheme_subscheme'),
        ),
    ]
